// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsmeRoaJVC6g54Oj8PYp0gRXgHeVrmURM',
    appId: '1:70749587736:web:930b3e23f3b12b3c4df66d',
    messagingSenderId: '70749587736',
    projectId: 'technicaltestfan',
    authDomain: 'technicaltestfan.firebaseapp.com',
    storageBucket: 'technicaltestfan.appspot.com',
    measurementId: 'G-NNCP5TQH0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANobtWAJYAyorTApGHI_oXVwW3lNKA6rA',
    appId: '1:70749587736:android:d47d416329f96e604df66d',
    messagingSenderId: '70749587736',
    projectId: 'technicaltestfan',
    storageBucket: 'technicaltestfan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKqGtszBETJjuI-4WhbE-fcc6_vFg9JsM',
    appId: '1:70749587736:ios:2ae337ef1d71c9ea4df66d',
    messagingSenderId: '70749587736',
    projectId: 'technicaltestfan',
    storageBucket: 'technicaltestfan.appspot.com',
    iosBundleId: 'com.example.technicaltestfan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKqGtszBETJjuI-4WhbE-fcc6_vFg9JsM',
    appId: '1:70749587736:ios:2ae337ef1d71c9ea4df66d',
    messagingSenderId: '70749587736',
    projectId: 'technicaltestfan',
    storageBucket: 'technicaltestfan.appspot.com',
    iosBundleId: 'com.example.technicaltestfan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsmeRoaJVC6g54Oj8PYp0gRXgHeVrmURM',
    appId: '1:70749587736:web:11aed707942d9d3d4df66d',
    messagingSenderId: '70749587736',
    projectId: 'technicaltestfan',
    authDomain: 'technicaltestfan.firebaseapp.com',
    storageBucket: 'technicaltestfan.appspot.com',
    measurementId: 'G-DPFS7C2HM1',
  );
}
